apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-lambda
resources:
  - namespace.yaml
  - lambda-serviceaccount.yaml
  - lambda-configmap.yaml
  - lambda-deployment.yaml
  - lambda-netpol.yaml
