apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: arc-ui
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/arc-ui
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: arc-ui
  wait: true
  timeout: 2m
