apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-nu
resources:
  - namespace.yaml
  - nu-serviceaccount.yaml
  - nu-configmap.yaml
  - nu-deployment.yaml
  - nu-idle-deployment.yaml
  - nu-netpol.yaml
