apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-delta
resources:
  - namespace.yaml
  - delta-serviceaccount.yaml
  - delta-configmap.yaml
  - delta-deployment.yaml
  - delta-netpol.yaml
