apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-iota
resources:
  - namespace.yaml
  - iota-serviceaccount.yaml
  - iota-configmap.yaml
  - iota-deployment.yaml
  - iota-netpol.yaml
