apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-mu
resources:
  - namespace.yaml
  - mu-serviceaccount.yaml
  - mu-configmap.yaml
  - mu-deployment.yaml
  - mu-idle-deployment.yaml
  - mu-netpol.yaml
