apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-zeta
resources:
  - namespace.yaml
  - zeta-serviceaccount.yaml
  - zeta-configmap.yaml
  - zeta-deployment.yaml
  - zeta-netpol.yaml
