apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-omicron
resources:
  - namespace.yaml
  - omicron-serviceaccount.yaml
  - omicron-configmap.yaml
  - omicron-deployment.yaml
  - omicron-netpol.yaml
